- name: data types
  host: localhost
  vars:
    Course: DevOps with AWS #string
    Tools: #list
    - Linux
    - Shell
    - Ansible
    Experience: #map or dictionary
      DevOps: 3 # number
      AWS: 2
      Docker: 1
    RealProject: true #boolean
  tasks:
  - name: print variables
    ansible.builtin.debug:
      msg: "Course: {{Course}}, Tool covered: {{Tools}}, Experience is: {{Experience}}, is ral project: {{RealProject}}"

