- name: install packages
  hosts: web
  become: yes
  tasks:
  - name: install packages
    ansible.builtin.debug:
      name: "{{item}}"
      state: latest
    loop:
    - {name: 'mysql', state: 'latest'}
    - {name: 'nginx', state: 'absent'}
    - {name: 'postfix', state: 'absent'}


